### ISSUE TITLE
Random txt is not a category on document card

### ISSUE THREAD

**Issue by McDKirra** [mikezimm/Pivot-Tiles#11]
What's this? see URL thing under tile pics

![image](https://user-images.githubusercontent.com/35781691/90038308-ef55b780-dccd-11ea-993d-1eeb526ff268.png)

**Comment by mikezimm** [comment]
## To resolve:
Need to update PivotTiles.tsx on public onChangePivotClick = (item): void => {
Right now it's passing heroCategory: 'randDomTextIsNotACategory'

It should be passing a value that is appropriate as the heroCategory based on the pivotCategory that was clicked.

For instance, if "TileCategory" pivot was clicked heroCategory would be the default one.
If "Modified" or "Created" was clicked, maybe pre-set to something that is the best "Hero Category".
Or show no hero panel because can I really know what is best?


## Test notes:
This came up for me when using the "DEV" version and I picked "OurTiles" list option... may be others but this is when I saw it.

It only happens when you have the second Pivot Category row "Change Pivots".
When I clicked all the categories, all the tiles show that text.

in PivotTiles.tsx around line 432, this is where it's coming from.

in PivotTiles.tsx around line 155, the gridLayout function getting passed the value:  this.state.heroCategory

in TileBuilder.tsx around line 251, the **location** is set to be the category passed when calling it...
Since the OnClick changes the 'heroCategory' property to '', it is getting displayed here.

## PivotTiles.tsx ~ line 432
```typescript
  public onChangePivotClick = (item): void => {
    //This sends back the correct pivot category which matches the category on the tile.
    let e: any = event;

    this._updateStateOnPropsChange({
      heroCategory: 'randDomTextIsNotACategory',
      newCatColumn: item.props.itemKey,
    });

  } //End onClick
```

## PivotTiles.tsx ~ line 155
```typescript
    if (this.state.setLayout === "Card") {
      tileBuild = tileBuilders.gridLayout(this.props,this.state,this.state.filteredTiles, this.state.heroCategory);
    } else if (this.state.setLayout === "List") {
      tileBuild = tileBuilders.listViewBuilder(this.props,this.state,this.state.filteredTiles, this.state.heroCategory);
    } else {
      tileBuild = tileBuilders.tileBuilder(this.props,this.state);
    }
```

## TileBuilder.tsx ~ line 251:
```typescript
export function gridLayout(parentProps,parentState, theseAreItems, thisCategory){
  // Carousel option from https://github.com/hugoabernier/WebPartDesignSeries
  console.log('gridLayout',parentProps,parentState, theseAreItems, thisCategory);
  let items = theseAreItems.map(item => ({

    thumbnail: item.imageUrl,
    title: item.title,
    name: item.description,
    profileImageSrc: "",
    location: thisCategory,
    activity: "",
    href: item.href,
    target: item.target,
    listWebURL:item.listWebURL,

  }));
```
